### ISSUE TITLE
workflow: nextflow path

### ISSUE THREAD

**Issue by joschrew** [joschrew/ocrd-webapi-implementation#10]
nextflow path should be configurable. In my case it was available in my PATH but not in PATH of server. So it should be possible to configure with absolute path

**Comment by MehmedGIT** [comment]
I think this belongs to the requirements: Installing Nextflow and making Nextflow accessible in the $PATH. On the API part, we can send a warning that Nextflow is not found on $PATH. This will also be valid for issue #9 - we can again send a warning if Nextflow is not found on server startup.

We can also make the Nextflow path configurable, but that should come as an addition. Not a must. The default path of Nextflow should still be searched in $PATH if the Nextflow path is not configured.
