### ISSUE TITLE
workflow: execute workflow endpoint

### ISSUE THREAD

**Issue by joschrew** [joschrew/ocrd-webapi-implementation#11]
change/think about execute workflow endpoint. currently the workspace_id is provided as query-parameter. This is working, but this is not described in the api description. So either one has to be changed, api-description or implementation

**Comment by joschrew** [comment]
not totally correct what I wrote. I think implementation and api-description have both to be changed

**Comment by MehmedGIT** [comment]
Agree that the API description should be changed. `POST /workflow/{workflow-id}` ([reference](https://app.swaggerhub.com/apis/kba/ocr-d_web_api/0.0.1#/workflow/runWorkflow)) should get an additional parameter `workspace_id`. What should be changed in the implementation part?

**Comment by joschrew** [comment]
I see two suitable options
    - `POST workflow/{workflow-id}/{workspace-id}`, so that workspace-id is provided in the request-path
    - provide a json-document in the post-body and put the workspace-id there. This offers the possibility to more easily add a file-grp or other parameters later as well if necessary.
I would not use a query-parameter, I don't know really why, but I think the two mentioned options are better. What would you prefer or is both equally good for you (or you don't care)?

**Comment by joschrew** [comment]
I created a Pull Request to extend the api. If this is accepted the method signature of the start_workflow Method should look like this:
`async def start_workflow(workflow_id: str, workspace_id: str = Body(), parameters: dict = Body()):` (alternatively, maybe better: https://fastapi.tiangolo.com/tutorial/body/)
A curl request would be like this:
`curl -X 'POST' 'http://localhost:8000/workflow/the-workflow-id' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{ "workspace_id": "test", "parameters": { "test": 10 }}'`

**Comment by joschrew** [comment]
mentioned pull request was merged a while a go and functionality is implemented
