### ISSUE TITLE
workflow: fix update workflow

### ISSUE THREAD

**Issue by joschrew** [joschrew/ocrd-webapi-implementation#7]
updating a workflow-skript does not work correctly. Just tested briefly. I think I tried `curl -X PUT http://localhost:8000/workflow/0c150d20-e3f7-491f-93ad-b285014e5993 -F nextflow_script=@nextflow.nf` and deleted the old workflow without generating the new one. I think the directory of the workflow is deleted (this is on purpose) but recreating the directory has been forgotten or not the workflow-dir must be deleted only the content.

**Comment by MehmedGIT** [comment]
Issue fixed, in commit: 8ab5a5670b2d89b00e77d7eb781320a8ffb41e0d

The directory was not created indeed. It was not forgotten just in the wrong scope.

**Comment by joschrew** [comment]
closed because it is working (although specified commit is not included in main-branch)
